{% set name = "ffnet" %}
{% set version = "0.8.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "1aaf35158239cd1e6f63504e884683abac87c77919af36cbefbf1169fed5d1a2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - numpy >=1.4
    - scipy >=0.8
  run:
    - python
    - numpy >=1.4
    - scipy >=0.8
    - networkx >=1.3

test:
  imports:
    - ffnet
    - ffnet.examples
    - ffnet.fortran

about:
  home: ffnet.sourceforge.net
  license: LGPL-3.0
  license_family: LGPL
  license_file: 'LICENSE'
  summary: Feed-forward neural network solution for python
  description: "=============================================\r\nffnet: feed-forward neural network for python\r\n=============================================\r\n\r\nBasic usage of the package is outlined\
    \ below:\r\n\r\n>>> from ffnet import ffnet, mlgraph, savenet, loadnet, exportnet\r\n>>> conec = mlgraph( (2,2,1) )\r\n>>> net = ffnet(conec)\r\n>>> input = [ [0.,0.], [0.,1.], [1.,0.], [1.,1.] ]\r\n\
    >>> target  = [ [1.], [0.], [0.], [1.] ]\r\n>>> net.train_tnc(input, target, maxfun = 1000)\r\n>>> net.test(input, target, iprint = 2)\r\n>>> savenet(net, \"xor.net\")\r\n>>> exportnet(net, \"xor.f\"\
    )\r\n>>> net = loadnet(\"xor.net\")\r\n>>> answer = net( [ 0., 0. ] )\r\n>>> partial_derivatives = net.derivative( [ 0., 0. ] )\r\n\r\nFor instalation instructions and documentation go to `http://ffnet.sourceforge.net\
    \ <http://ffnet.sourceforge.net>`_.\r\n\r\n**Note: ffnet has now a graphical user interface** `ffnetui <https://pypi.python.org/pypi/ffnetui>`_.\r\n\r\n\r\n\r\nRelease notes\r\n-------------\r\n\r\n\
    0.8.3\r\n+++++\r\nLicense switched to LGPL. Only minor updates in code are performed, no API changes are made. Along with this version, new graphical user interface ffnetui-0.8.3 has been released.\r\
    \n\r\n0.8.0\r\n+++++\r\nThis version supports python 3. Only minor changes in code (and no API changes) are made in comparison to previous release, all scripts should run without problems."

extra:
  recipe-maintainers:
    - SolarDrew

